theory:
  classy:
    extra_args:
      output: "mPk"
      # non linear: 'none'             
      P_k_max_h/Mpc: 30
      N_ncdm: 1
      N_ur: 2.0328
      Omega_Lambda: 0
    stop_at_error: False
    input_params:
    - As
    - omega_cdm
    - w
    - wa
    - 100*theta_s
    - ns
    - omega_b
    - tau
    - Omega_k
    - m_ncdm
  FSBAO_likelihood_gc_w0watau_direct.Taylor_pk_theory_zs:
      zfids:
      - 0.30
      - 0.51
      - 0.71
      - 0.92
      - 1.32
      - 1.49
      bao_sample_names:
      - BGS
      - LRG1
      - LRG2
      - LRG3
      - ELG
      - QSO
      Rsmooth:
      - 15
      - 15
      - 15
      - 15
      - 15
      - 30
      fid_dists: 
      - [117.3640762885204, 833.3078565389818]
      - [133.05386526145136,1337.692980282394]
      - [150.38072236661685,1761.8521557340339]
      - [170.78364036132075, 2154.866559272748]
      - [215.0091653164908, 2781.0509683317605]
      - [235.6651691492499, 3007.4665466663487]
      stop_at_error: True

likelihood:
  # planck_NPIPE_highl_CamSpec.TTTEEE:
  planck_2018_lowl.TT: null
  planck_2018_lowl.EE: null
  planck_NPIPE_highl_CamSpec.TTTEEE: null
  act_dr6_lenslike.ACTDR6LensLike:
    stop_at_error: true
    lens_only: false
    no_actlike_cmb_corrections: true
    lmax: 4000
    variant: actplanck_baseline
  DESI_RSDBAO_BGS:
    class: FSBAO_likelihood_gc_w0watau_direct.JointLikelihood
    basedir: ./data/DR1/spec_z_dat/
    linear_param_dict_fn: ./likelihoods/desi_fs_bao_bgs_linear_params.yaml
    template_fn: pk_dat/templates_BGS_desifid.txt
    photo_tmp: False
    zfids:
    - 0.30
    fs_sample_names:
    - BGS
    fs_datfns:
    - pk_dat/Pk_BGS_desifid.txt
    covfn: pk_cov/cov_rsd_BAO_BGS_desifid.txt
    fs_matWfns:
    - pk_wmats/wmat_BGS_desifid.txt
    w_kin_fn: pk_wmats/wmat_xin_BGS_desifid.txt
    fs_kmins:
    - 0.02
    fs_mmaxs:
    - 0.2
    fs_qmaxs:
    - 0.2
    fs_hmaxs:
    - 0.0
    bao_sample_names:
    - BGS
    bao_datfns:
    - pk_dat/Xi_post_BGS_desifid.txt
    bao_rmins:
    - 80.
    bao_rmaxs:
    - 130.
    bao_ells: [0]
    
    include_priors: true
    optimize: false
    stop_at_error: true
    cov_fac: 1.0
    invcov_fac: 1.0 
    #invcov_fac: 0.874
    hexa: false
    jeff: false
    AP_scale: true
    bsig8: 1.0
    
  DESI_RSDBAO_LRGz1:
    class: FSBAO_likelihood_gc_w0watau_direct.JointLikelihood
    basedir: ./data/DR1/spec_z_dat/
    linear_param_dict_fn: ./likelihoods/desi_fs_bao_lrgz1_linear_params.yaml
    template_fn: pk_dat/templates_LRG1_desifid.txt
    photo_tmp: False
    zfids:
    - 0.51
    fs_sample_names:
    - LRG1
    fs_datfns:
    - pk_dat/Pk_LRG1_desifid.txt
    covfn: pk_cov/cov_rsd_BAO_LRG1_desifid.txt
    fs_matWfns:
    - pk_wmats/wmat_LRG1_desifid.txt
    w_kin_fn: pk_wmats/wmat_xin_LRG1_desifid.txt
    fs_kmins:
    - 0.02
    fs_mmaxs:
    - 0.2
    fs_qmaxs:
    - 0.2
    fs_hmaxs:
    - 0.0
    bao_sample_names:
    - LRG1
    bao_datfns:
    - pk_dat/Xi_post_LRG1_desifid.txt
    bao_rmins:
    - 80.
    bao_rmaxs:
    - 130.
    bao_ells: [0,2]
    include_priors: true
    optimize: false
    stop_at_error: true
    cov_fac: 1.0
    invcov_fac: 1.0 
    #invcov_fac: 0.874
    hexa: false
    jeff: false
    AP_scale: true
    bsig8: 1.0
    
  DESI_RSDBAO_LRGz2:
    class: FSBAO_likelihood_gc_w0watau_direct.JointLikelihood
    basedir: ./data/DR1/spec_z_dat/
    linear_param_dict_fn: ./likelihoods/desi_fs_bao_lrgz2_linear_params.yaml
    template_fn: pk_dat/templates_LRG2_desifid.txt
    photo_tmp: False
    zfids:
    - 0.71
    fs_sample_names:
    - LRG2
    fs_datfns:
    - pk_dat/Pk_LRG2_desifid.txt
    covfn: pk_cov/cov_rsd_BAO_LRG2_desifid.txt
    fs_matWfns:
    - pk_wmats/wmat_LRG2_desifid.txt
    w_kin_fn: pk_wmats/wmat_xin_LRG2_desifid.txt
    fs_kmins:
    - 0.02
    fs_mmaxs:
    - 0.2
    fs_qmaxs:
    - 0.2
    fs_hmaxs:
    - 0.0
    bao_sample_names:
    - LRG2
    bao_datfns:
    - pk_dat/Xi_post_LRG2_desifid.txt
    bao_rmins:
    - 80.
    bao_rmaxs:
    - 130.
    bao_ells: [0,2]
    include_priors: true
    optimize: false
    stop_at_error: true
    cov_fac: 1.0
    invcov_fac: 1.0 
    #invcov_fac: 0.874
    hexa: false
    jeff: false
    AP_scale: true
    bsig8: 1.0
    
  DESI_RSDBAO_LRGz3:
    class: FSBAO_likelihood_gc_w0watau_direct.JointLikelihood
    basedir: ./data/DR1/spec_z_dat/
    linear_param_dict_fn: ./likelihoods/desi_fs_bao_lrgz3_linear_params.yaml
    template_fn: pk_dat/templates_LRG3_desifid.txt
    photo_tmp: False
    zfids:
    - 0.92
    fs_sample_names:
    - LRG3
    fs_datfns:
    - pk_dat/Pk_LRG3_desifid.txt
    covfn: pk_cov/cov_rsd_BAO_LRG3_desifid.txt
    fs_matWfns:
    - pk_wmats/wmat_LRG3_desifid.txt
    w_kin_fn: pk_wmats/wmat_xin_LRG3_desifid.txt
    fs_kmins:
    - 0.02
    fs_mmaxs:
    - 0.2
    fs_qmaxs:
    - 0.2
    fs_hmaxs:
    - 0.0
    bao_sample_names:
    - LRG3
    bao_datfns:
    - pk_dat/Xi_post_LRG3_desifid.txt
    bao_rmins:
    - 80.
    bao_rmaxs:
    - 130.
    bao_ells: [0,2]
    include_priors: true
    optimize: false
    stop_at_error: true
    cov_fac: 1.0
    invcov_fac: 1.0 
    #invcov_fac: 0.874
    hexa: false
    jeff: false
    AP_scale: true
    bsig8: 1.0

  DESI_RSDBAO_ELG:
    class: FSBAO_likelihood_gc_w0watau_direct.JointLikelihood
    basedir: ./data/DR1/spec_z_dat/
    linear_param_dict_fn: ./likelihoods/desi_fs_bao_elg_linear_params.yaml
    template_fn: pk_dat/templates_ELG_desifid.txt
    photo_tmp: True
    zfids:
    - 1.32
    fs_sample_names:
    - ELG
    fs_datfns:
    - pk_dat/Pk_ELG_desifid.txt
    covfn: pk_cov/cov_rsd_BAO_ELG_desifid.txt
    fs_matWfns:
    - pk_wmats/wmat_ELG_desifid.txt
    w_kin_fn: pk_wmats/wmat_xin_ELG_desifid.txt
    fs_kmins:
    - 0.02
    fs_mmaxs:
    - 0.2
    fs_qmaxs:
    - 0.2
    fs_hmaxs:
    - 0.0
    bao_sample_names:
    - ELG
    bao_datfns:
    - pk_dat/Xi_post_ELG_desifid.txt
    bao_rmins:
    - 80.
    bao_rmaxs:
    - 130.
    bao_ells: [0,2]
    include_priors: true
    optimize: false
    stop_at_error: true
    cov_fac: 1.0
    invcov_fac: 1.0 
    #invcov_fac: 0.874
    hexa: false
    jeff: false
    AP_scale: true
    bsig8: 1.0

  DESI_RSDBAO_QSO:
    class: FSBAO_likelihood_gc_w0watau_direct.JointLikelihood
    basedir: ./data/DR1/spec_z_dat/
    linear_param_dict_fn: ./likelihoods/desi_fs_bao_qso_linear_params.yaml
    template_fn: pk_dat/templates_QSO_desifid.txt
    photo_tmp: True
    zfids:
    - 1.49
    fs_sample_names:
    - QSO
    fs_datfns:
    - pk_dat/Pk_QSO_desifid.txt
    covfn: pk_cov/cov_rsd_BAO_QSO_desifid.txt
    fs_matWfns:
    - pk_wmats/wmat_QSO_desifid.txt
    w_kin_fn: pk_wmats/wmat_xin_QSO_desifid.txt
    fs_kmins:
    - 0.02
    fs_mmaxs:
    - 0.2
    fs_qmaxs:
    - 0.2
    fs_hmaxs:
    - 0.0
    bao_sample_names:
    - QSO
    bao_datfns:
    - pk_dat/Xi_post_QSO_desifid.txt
    bao_rmins:
    - 80.
    bao_rmaxs:
    - 130.
    bao_ells: [0]
    include_priors: true
    optimize: false
    stop_at_error: true
    cov_fac: 1.0
    invcov_fac: 1.0 
    #invcov_fac: 0.874
    hexa: false
    jeff: false
    AP_scale: true
    bsig8: 1.0

    
params:
  w:
    prior:
      min: -2.0
      max: -0.1
    ref:
      dist: norm
      loc: -1.0
      scale: 0.05
    latex: w_0
  wa:
    prior:
      min: -3.0
      max: 0.5
    ref:
      dist: norm
      loc: 0.0
      scale: 0.05
    latex: w_{a}
  omega_b:
    prior: 
      min: 0.017
      max: 0.027
    ref: 
      dist: norm
      loc: 2.237e-2
      scale: 3e-4
    proposal: 1.5e-4
    latex: \Omega_bh^2
  omega_cdm:
    prior:
      min: 0.08
      max: 0.16
    ref:
      dist: norm
      loc: 0.12
      scale: 0.05
    latex: \Omega_\mathrm{cdm}h^2
  logA:
    # value: 3.0363942552728806
    prior:
      dist: uniform
      min:  2.03
      max:  4.03
      # min:  1.61
      # max:  3.91
    ref:
      dist:  norm
      loc:   3.03694
      scale: 0.05
    latex: \log(10^{10} A_\mathrm{s})
  tau:
    prior:
      dist: norm
      loc: 0.06
      scale: 0.006
    proposal: 0.006
    latex: \tau_\mathrm{reio}
  
  theta_s_100: 
    # value: 1.0411
    prior: 
      min: 1.038
      max: 1.044
    ref: 
      dist: norm
      loc: 1.0411
      scale: 6.2e-4
    # latex: 100\theta_\mathrm{s}
  100*theta_s:
    value: 'lambda theta_s_100: theta_s_100'
    derived: False
    latex: 100\theta_\mathrm{s}
  ns:
    prior: 
      min: 0.9
      max: 1.1
    ref: 
      dist: norm
      loc: 0.9649
      scale: 8.4e-3
    proposal: 4.2e-3
    latex: n_s
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  Omega_k:
    value: 0.0
    latex: \Omega_k
  m_ncdm:
    value: 0.06
    latex: M_{\nu}
  # H0_emu:
  #   latex: H_0^{emu}
  H0:
    latex: H_0
  h:
    latex: h
  rs_drag:
    latex: r_\mathrm{drag}
  sigma8:
    latex: \sigma_8
  omegam:
    latex: \Omega_\mathrm{m}
  
  
    
  # BGS
  bsig8_BGS:
    prior:
      dist: uniform
      min:  0.5
      max:  3.0
    ref:
      dist:  norm
      loc:   1.13
      scale: 0.05
    latex: (1+b_1^{BGS})\sigma_8
  b2sig8_BGS:
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   -0.1
      scale: 0.5
    latex: b_2\sigma_8^{BGS}
  bssig8_BGS:
    # value: 0.0
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   0.04
      scale: 0.5
    latex: b_s\sigma_8^{BGS}
    
  # LRG1
  bsig8_LRG1:
    prior:
      dist: uniform
      min:  0.5
      max:  3.0
    ref:
      dist:  norm
      loc:   1.18
      scale: 0.05
    latex: (1+b_1^{LRG1})\sigma_8
  b2sig8_LRG1:
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   -0.16
      scale: 0.5
    latex: b_2\sigma_8^{LRG1}
  bssig8_LRG1:
    # value: 0.0
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   0.12
      scale: 0.5
    latex: b_s\sigma_8^{LRG1}
  
  
  # LRG2
  bsig8_LRG2:
    prior:
      dist: uniform
      min:  0.5
      max:  3.0
    ref:
      dist:  norm
      loc:   1.16
      scale: 0.05
    latex: (1+b_1^{LRG2})\sigma_8
  b2sig8_LRG2:
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   -0.28
      scale: 0.5
    latex: b_2\sigma_8^{LRG2}
  bssig8_LRG2:
    # value: 0.0
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   0.18
      scale: 0.5
    latex: b_s\sigma_8^{LRG2}

    
  # LRG3
  bsig8_LRG3:
    prior:
      dist: uniform
      min:  0.5
      max:  3.0
    ref:
      dist:  norm
      loc:   1.14
      scale: 0.05
    latex: (1+b_1^{LRG3})\sigma_8
  b2sig8_LRG3:
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   -0.6
      scale: 0.5
    latex: b_2\sigma_8^{LRG3}
  bssig8_LRG3:
    # value: 0.0
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   0.5
      scale: 0.5
    latex: b_s\sigma_8^{LRG3}

  # ELG
  bsig8_ELG:
    prior:
      dist: uniform
      min:  0.5
      max:  3.0
    ref:
      dist:  norm
      loc:   1.7239232
      scale: 0.05
    latex: (1+b_1^{ELG})\sigma_8
  b2sig8_ELG:
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   -2.1724898
      scale: 0.1
    latex: b_2\sigma_8^{ELG}
  bssig8_ELG:
    # value: 0.0
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   1.0970124
      scale: 0.1
    latex: b_s\sigma_8^{ELG}
  # QSO
  bsig8_QSO:
    prior:
      dist: uniform
      min:  0.5
      max:  3.0
    ref:
      dist:  norm
      loc:   1.7239232
      scale: 0.05
    latex: (1+b_1^{QSO})\sigma_8
  b2sig8_QSO:
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   -2.1724898
      scale: 0.1
    latex: b_2\sigma_8^{QSO}
  bssig8_QSO:
    # value: 0.0
    prior:
      # dist: uniform
      # min:  -5.0
      # max:  5.0
      dist:  norm
      loc:   0.0
      scale: 5
    ref:
      dist:  norm
      loc:   1.0970124
      scale: 0.1
    latex: b_s\sigma_8^{QSO}

    
  b3sig8_BGS:
    value: 0.0
    latex: b_3\sigma_8^{BGS}
  b3sig8_LRG3:
    value: 0.0
    latex: b_3\sigma_8^{LRG3}
  b3sig8_LRG2:
    value: 0.0
    latex: b_3\sigma_8^{LRG2}
  b3sig8_LRG1:
    value: 0.0
    latex: b_3\sigma_8^{LRG1}
  b3sig8_ELG:
    value: 0.0
    latex: b_3\sigma_8^{ELG}
  b3sig8_QSO:
    value: 0.0
    latex: b_3\sigma_8^{QSO}
  


  # BAO
  B1_BGS:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 1.12
      scale: 0.1
    latex: B_1^{BGS}
  F_BGS:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.63
      scale: 0.1
    latex: F^{BGS}
  Sigpar_BGS:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\parallel}^{BGS}   
  Sigperp_BGS:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 1.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\perp}^{BGS}
  Sigs_BGS:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 2.0
    #   scale: 0.1
    latex: \Sigma_{s}^{BGS}
  
  B1_LRG1:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 1.12
      scale: 0.1
    latex: B_1^{LRG1}
  F_LRG1:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.63
      scale: 0.1
    latex: F^{LRG1}
    
  Sigpar_LRG1:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\parallel}^{LRG1}   
  Sigperp_LRG1:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 1.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\perp}^{LRG1}
  Sigs_LRG1:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 2.0
    #   scale: 0.1
    latex: \Sigma_{s}^{LRG1}
    
  B1_LRG2:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 1.12
      scale: 0.1
    latex: B_1^{LRG2}
  F_LRG2:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.63
      scale: 0.1
    latex: F^{LRG2}
    
  Sigpar_LRG2:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\parallel}^{LRG2}   
  Sigperp_LRG2:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 1.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\perp}^{LRG2}
  Sigs_LRG2:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 2.0
    #   scale: 0.1
    latex: \Sigma_{s}^{LRG2}
    
  B1_LRG3:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 1.12
      scale: 0.1
    latex: B_1^{LRG3}
  F_LRG3:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.63
      scale: 0.1
    latex: F^{LRG3}
  Sigpar_LRG3:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\parallel}^{LRG3}   
  Sigperp_LRG3:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 1.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\perp}^{LRG3}
  Sigs_LRG3:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 2.0
    #   scale: 0.1
    latex: \Sigma_{s}^{LRG3}

  B1_ELG:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 1.12
      scale: 0.1
    latex: B_1^{ELG}
  F_ELG:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.63
      scale: 0.1
    latex: F^{ELG}
  Sigpar_ELG:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\parallel}^{ELG}   
  Sigperp_ELG:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 1.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\perp}^{ELG}
  Sigs_ELG:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 2.0
    #   scale: 0.1
    latex: \Sigma_{s}^{ELG}
    
  B1_QSO:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 1.12
      scale: 0.1
    latex: B_1^{QSO}
  F_QSO:
    prior:
      dist: uniform
      min: 0.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.63
      scale: 0.1
    latex: F^{QSO}
  Sigpar_QSO:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\parallel}^{QSO}   
  Sigperp_QSO:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 1.0
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.1
    latex: \Sigma_{\perp}^{QSO}
  Sigs_QSO:
    value: 0.0
    # prior:
    #   dist: norm
    #   loc: 0.0
    #   scale: 2.0
    # ref:
    #   dist: norm
    #   loc: 2.0
    #   scale: 0.1
    latex: \Sigma_{s}^{QSO}
    
    
sampler:
  mcmc:
    # covmat: auto
    learn_proposal: True
    learn_proposal_Rminus1_max: 30.0
    # learn_proposal_Rminus1_max_early: 30.0
    output_every: 60s
    measure_speeds: True
    max_tries: 500
    drag: False
    oversample_power: 0.4
    proposal_scale: 1.5
    Rminus1_stop: 0.01
    # blocking:
    #   - [ 1, [w,wa,omega_b,omega_cdm,logA,tau,ns,theta_s_100]]
    #   # - [ 1, [logA,omega_b,omega_cdm,H0]]
    #   - [ 6, [bsig8_BGS,b2sig8_BGS,bssig8_BGS,bsig8_LRG1,b2sig8_LRG1,bssig8_LRG1,bsig8_LRG2,b2sig8_LRG2,bssig8_LRG2,bsig8_LRG3,b2sig8_LRG3,bssig8_LRG3,bsig8_ELG,b2sig8_ELG,bssig8_ELG,bsig8_QSO,b2sig8_QSO,bssig8_QSO]]
    #   - [6,[B1_BGS,F_BGS,B1_LRG1,F_LRG1,B1_LRG2,F_LRG2,B1_LRG3,F_LRG3,B1_ELG,F_ELG,B1_QSO,F_QSO]]
    
output: chains/test/chain
# debug: True
# debug_file: chains/w0wa/base_union3/class/chain
timing: True
stop_on_error: True
    
  
    
  
  